{{- $releaseName := .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: emr
  labels:
    app.kubernetes.io/name: emr
    chart: {{ template "ph-core-emr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app.kubernetes.io/name: emr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr
  labels:
    app.kubernetes.io/name: emr
    chart: {{ template "ph-core-emr.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: emr
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: emr
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: emr
        image: "{{ .Values.emr.image }}:{{ .Values.emr.tag }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "20m"
            memory: "128M"
          limits:
            cpu: "50m"
            memory: "256M"
        ports:
        - containerPort: 5000
        env:
          - name: AIDBOX_BASE_URL
            value: "https://aidbox.fhirlab.net/"
          {{- range $key, $value := .Values.EMRexternalSecretsNames }}
            {{- if $value.envVar }}
          - name: {{ $value.envVar }}
            valueFrom:
              secretKeyRef:
                name: {{ $releaseName }}-{{ $key }}
                key: {{ $key }}
            {{- end }}
          {{- end }}
