services:
  sdc:
    image: bedasoftware/fhir-sdc:1.0.0a10
    depends_on:
      devbox-healthcheck:
        condition: service_healthy
    links:
      - devbox
    env_file:
      - ./env/sdc
    tty: true
  devbox:
    image: healthsamurai/aidboxone:edge
    depends_on:
      - devbox-db
    links:
      - "devbox-db:database"
    ports:
      - "8080:8080"
    env_file:
      - ./env/aidbox
      - .env
    volumes:
      - ./resources:/resources
  devbox-db:
    image: "healthsamurai/aidboxdb:13.2"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbox
  devbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - devbox
    depends_on:
      - devbox
    healthcheck:
      test: curl --fail http://devbox:8080/health || exit 1
      interval: 5s
      timeout: 30s
      retries: 100
  build-seeds:
    image: bedasoftware/fhirsnake:latest
    command:
      - export
      - --output
      - /app/resources/initBundle.json
    volumes:
      - ./resources/seeds:/app/resources
  watch-seeds:
    image: bedasoftware/fhirsnake:latest
    command:
      - watch
      - --external-fhir-server-url
      - http://root:secret@devbox:8080
    volumes:
      - ./resources/seeds:/app/resources
  fhir-converters-app:
    image: bedasoftware/aidbox-fhir-converter:main
    depends_on:
      devbox-healthcheck:
        condition: service_healthy
    env_file:
      - ./env/fhir-converters-app
