emr:
  image: ghcr.io/beda-software/ph-core-connectathon
  tag: latest
converter:
  image: bedasoftware/aidbox-fhir-converter
  tag: main
  aidbox_init_url: http://aidbox:8080 # service that expose aidbox
  app_url: http://converter:8081
  secrets:
#   beda-app-init-1:
#     envVar: AIDBOX_CLIENT_ID # id of aidbox root client, it should have full access to API to be able to register adc aidbox app.
#   beda-app-init-2:
#     envVar: AIDBOX_CLIENT_SECRET # secret for aidbox root client
#   beda-app-init-3:
#     envVar: APP_SECRET # uniq string that will be used to identify requests from the app
sdc:
  image: bedasoftware/fhir-sdc
  tag: 1.0.0a11
  aidbox_init_url: http://aidbox:8080 # service that expose aidbox
  app_url: http://sdc:8081
  secrets:
#   beda-app-init-1:
#     envVar: APP_INIT_CLIENT_ID # id of aidbox root client, it should have full access to API to be able to register adc aidbox app.
#   beda-app-init-2:
#     envVar: APP_INIT_CLIENT_SECRET # secret for aidbox root client
#   beda-app-init-3:
#     envVar: APP_SECRET # uniq string that will be used to identify requests from the app
